version: '3.7'

services:
  
  backend:
    build: ./backend
    container_name: paruzorus-backend
    restart: always
    networks:
      - app-network
    ports:
      - 127.0.0.1:8000:8000
  
  frontend:
    build: ./frontend
    container_name: paruzorus-frontend
    restart: always
    networks:
      - app-network
    ports:
      - 127.0.0.1:3000:3000
  
  proxy:
    image: nginx:latest
    container_name: paruzorus-proxy
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
    depends_on: 
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge