version: '3.7'

services:
  
  webserver:
    build: ./webserver
    container_name: paruzorus-webserver
    restart: always
    networks:
      - app-network
    ports:
      - 127.0.0.1:8000:8000
  
  frontend:
    build: ./frontend
    container_name: paruzorus-frontend
    restart: always
    networks:
      - app-network
    ports:
      - 127.0.0.1:3000:3000
  
  proxy:
    build: ./nginx
    container_name: paruzorus-proxy
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge