version: '3.7'

services:

  webserver:
    build: ./webserver
    container_name: paruzorus-webserver
    restart: always
    ports:
      - 8000:8000
  
  frontend:
    build: ./frontend
    container_name: paruzorus-frontend
    ports:
      - 3000:3000
    restart: always

  nginx:
    build: ./nginx
    container_name: paruzorus-nginx
    restart: always
    depends_on:
    - webserver
    - frontend
    ports:
    - 1337:80