version: '3.7'

services:
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./conf:/etc/letsencrypt
      - ./www:/var/www/certbot
  
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --register-unsafely-without-email --rsa-key-size 4096 --agree-tos -d paruzorus.ddns.net
    volumes:
        - ./conf:/etc/letsencrypt
        - ./logs:/var/log/letsencrypt
        - ./www:/var/www/certbot
    depends_on: 
      - nginx